package mcli;

@:autoBuild(mcli.internal.Macro.build())
class CommandLine
{
	public function new()
	{
	}

	/**
		This function will be auto-generated by the build macro
	**/
	public function getArguments():Array<mcli.internal.Data.Argument>
	{
		return null;
	}

	public function showUsage():String
	{
		return mcli.Dispatch.showUsageOf(getArguments());
	}

	public function toString():String
	{
		return showUsage();
	}
}
