package mcli;

@:autoBuild(mcli.internal.Macro.build())
@:keepSub
class CommandLine
{
	private var _preventDefault:Bool = false;

	public function new()
	{
	}

	/**
		This function will be auto-generated by the build macro
	**/
	public function getArguments():Array<mcli.internal.Data.Argument>
	{
		return [];
	}

	/**
		Do not run default (`runDefault`)
	 **/
	public function preventDefault()
	{
		this._preventDefault = true;
	}

	public function showUsage():String
	{
		return mcli.Dispatch.showUsageOf(getArguments());
	}

	public function toString():String
	{
		return showUsage();
	}
}
